### ISSUE TITLE
🧑‍🍳 Main Menu

### ISSUE THREAD

**Issue by DaanKorver** [JustinLung/the-game-of-tones-chapterpage#4]
As a user, I want to navigate on the main menu, so that I can switch through different lessons.

Requirements:
- [ ] Chapter Navigation
- [x] Rainbow Gradient
- [x] Menu animation
- [x] DoD

**Comment by DaanKorver** [comment]
Zoals besproken, de functionaliteit word later behandeld, ready for tests!

**Comment by JustinLung** [comment]
LGTM
