### ISSUE TITLE
🚢 Onboarding

### ISSUE THREAD

**Issue by JustinLung** [JustinLung/the-game-of-tones-chapterpage#8]
As a user, I want a carousel with an onboarding text so that I know what the web app is all about.

Requirements:
- [x] Carousel with text
- [x] Automatic Carousel after a couple of seconds of doing nothing

**Comment by JustinLung** [comment]
Alright let's goo.... ready for testing @DaanKorver

**Comment by DaanKorver** [comment]
Check requirements pls @JustinLung
