### ISSUE TITLE
🪵 Log In Page

### ISSUE THREAD

**Issue by JustinLung** [JustinLung/the-game-of-tones-chapterpage#9]
As a user, I want to see a log in screen, so that I can access the main web app

Requirements:
- [x] Inputs

**Comment by JustinLung** [comment]
@DaanKorver ready for testing

**Comment by DaanKorver** [comment]
- Background color not the same as in the design
- Input colors not accurate, they look weird
- Position of all the elements need to be centered

**Comment by JustinLung** [comment]
fixed the issues and as discussed it is now very very legit ;)
